name: Build, Test and Deploy AIRKit Example Site

on:
  push:
    branches: ["main", "fix/skip-deploy-with-pr"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-test:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint code
        run: npm run lint

      - name: Build Auth frontend (root path)
        run: NODE_ENV=production npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  deploy:
    needs: build-and-test
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: main
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTION_ROLE }}
          role-session-name: github-actions-deploy
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync S3
        run: |
          aws s3 sync ./dist s3://${{ vars.AIR_EXAMPLE_BUCKET_NAME }}/airkit-example

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.AIR_EXAMPLE_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/airkit-example/*'
